# Generated by Django 4.0.5 on 2022-07-08 07:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_post_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='smsMessage',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='userNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='Notification/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('utimestamp', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studentNT', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '8.Mobile-Notifications',
            },
        ),
    ]
