# Generated by Django 4.0.5 on 2022-07-16 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_user_smsmessage_usernotification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usernotification',
            options={'verbose_name_plural': 'Mobile-Notifications'},
        ),
    ]
