
name: Django CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.10.12]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run 
      run: |
       python3 manage.py test
  deploy:
        runs-on: ubuntu-latest
        name: Deploy to EC2
        steps:
          -name: ssh -i "ubuntu.pem" ubuntu@ec2-13-235-128-168.ap-south-1.compute.amazonaws.com
          -uses: appleboy/ssh-action@master
          with:
          -host: ${{ secrets.HOST }}
          -username: ${{ secrets.USERNAME }}
          -port: ${{ secrets.PORT }}
          -key: ${{ secrets.SSHKEY }}
           -script: "cd /home/ubuntu/web/django && ./.scripts/deploy.sh"  
